github:
  description: "ASF Corporate Treasurer Information"
  homepage: https://treasurer.apache.org/
  features:
    # Enable issue management
    issues: true

pelican:
  notify:         team@treasurer.apache.org
  target:         asf-site
  theme:          theme/apache
  whoami:         main

staging:
  profile:  ~
  whoami:   asf-site
